### PR TITLE
Bump the maven plugin version to work nice with Mac/Java 1.7

### PR DESCRIPTION
**Pull request by MatejBalantic**
Had hard time running mvn package from shell on Mac (worked fine with Ubuntu).
The only thing that really helped was bumping maven plugin.

I am not sure it makes sense to push this to master, so feel free to reject the PR if you think it's dangerous.

### CODE REVIEW

**Comment by leocwolter** [comment]
Sorry for the delay. Did you test it with ubuntu?

**Comment by MatejBalantic** [comment]
Not sure, have no Ubuntu at hand. Can anyone try and verify?

**Comment by csokol** [comment]
Hi, @MatejBalantic, since it looks like no one with a linux box can test it, I'll merge it and if any linux user gets a problem with that in the future I hope a new issue will be opened :-)

Thanks!

**Comment by JamesSullivan** [comment]
I have been running it with Ubuntu 14.04 and have not noticed any issues

**Pull request merged**
